### ISSUE TITLE
bump `setup go` in GHA

### ISSUE THREAD

**Issue by chrismarget-j** [Juniper/apstra-go-sdk#310]
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default

Warning we're getting from GHA right now:
```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab, actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

Probably want to bump both the `setup-go` action and the go version to 1.22.5

```yaml
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: '1.22.5'
```
